# Generated by Django 3.0.3 on 2020-03-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_system.Inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_system.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(through='item_system.Quantity', to='item_system.Item'),
        ),
    ]
