# Generated by Django 3.0.3 on 2020-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_system', '0002_auto_20200308_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='seeds', max_length=10),
            preserve_default=False,
        ),
    ]
