# Generated by Django 3.0.3 on 2020-02-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0003_friends_friendslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_network.Inbox')),
            ],
        ),
    ]
