# Generated by Django 3.0.3 on 2020-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='isRequest',
            field=models.BooleanField(default=False),
        ),
    ]
