# Generated by Django 3.0.3 on 2020-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0005_messages_isrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent_from',
            field=models.CharField(default='plant', max_length=100),
            preserve_default=False,
        ),
    ]
