# Generated by Django 3.0.3 on 2020-03-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0006_messages_sent_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFirstVisit',
            field=models.BooleanField(default=True),
        ),
    ]
