# Generated by Django 3.0.3 on 2020-03-04 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0008_messages_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
