# Generated by Django 3.0.3 on 2020-03-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0009_messages_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend_pic',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='username',
        ),
        migrations.AddField(
            model_name='friends',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='plant_network.Profile'),
            preserve_default=False,
        ),
    ]
