# Generated by Django 3.0.3 on 2020-03-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0010_auto_20200305_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_network.Profile'),
        ),
    ]
