# Generated by Django 3.0.3 on 2020-03-07 02:16

from django.db import migrations, models
import plant_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_network', '0011_auto_20200306_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', max_length=300, validators=[plant_network.models.validate_img]),
        ),
    ]
