# Generated by Django 3.0.3 on 2020-02-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
    ]
