# Generated by Django 3.0.3 on 2020-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0002_remove_plant_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
