# Generated by Django 3.0.3 on 2020-02-26 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0008_auto_20200226_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
