# Generated by Django 3.0.3 on 2020-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0009_payment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
