# Generated by Django 3.0.3 on 2020-02-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0010_plant_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
