# Generated by Django 3.0.3 on 2020-02-26 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('plant_gallery', '0011_plant_for_sale'),
    ]

    operations = [

    ]
