# Generated by Django 3.0.3 on 2020-03-07 02:36

from django.db import migrations, models
import plant_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(validators=[plant_gallery.models.validate_card_number]),
        ),
    ]
