# Generated by Django 3.0.3 on 2020-03-07 03:19

from django.db import migrations, models
import plant_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0013_auto_20200307_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, validators=[plant_gallery.models.validate_card_number]),
        ),
    ]
