# Generated by Django 3.0.3 on 2020-03-07 03:54

from django.db import migrations, models
import plant_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0015_auto_20200307_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.CharField(max_length=2, validators=[plant_gallery.models.validate_month]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.CharField(max_length=4, validators=[plant_gallery.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='zip',
            field=models.CharField(max_length=5, validators=[plant_gallery.models.validate_zip]),
        ),
    ]
