# Generated by Django 3.0.3 on 2020-03-07 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0017_auto_20200307_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter alphabetic characters only.', regex='^[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter alphabetic characters only.', regex='^[a-zA-Z]+')]),
        ),
    ]
