# Generated by Django 3.0.3 on 2020-03-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0019_auto_20200307_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
