# Generated by Django 3.0.3 on 2020-03-10 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0020_auto_20200310_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter alphabetic characters only.', regex='^[a-zA-Z]*$')]),
        ),
    ]
