# Generated by Django 3.0.3 on 2020-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0021_auto_20200310_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='max_exp',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
    ]
