# Generated by Django 3.0.3 on 2020-03-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_gallery', '0022_auto_20200310_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='max_level',
            field=models.IntegerField(default=5),
        ),
    ]
